#!/bin/sh
set -eu
case "${1:-}" in
  test) shift; exec docker compose run --rm controller python -m unittest discover -s tests "$@" ;;
  stage9) shift; exec docker compose run --rm controller python -m unittest \
      tests.test_stage9_supervisor tests.test_stage9_long_horizon "$@" ;;
  *) exec docker compose run --rm controller python -m factory_controller.cli "$@" ;;
esac
