from enum import Enum


class MissionState(str, Enum):
    PCP_APPROVED = "PCP_APPROVED"
    ENGINEERING = "ENGINEERING"
    VERIFYING = "VERIFYING"
    VERIFIED_RC = "VERIFIED_RC"
    OWNER_VALIDATION = "OWNER_VALIDATION"
    DISTRIBUTION_READY = "DISTRIBUTION_READY"
    BLOCKED = "BLOCKED"
    DISTRIBUTED = "DISTRIBUTED"


REQUIRED_FORWARD = (
    MissionState.PCP_APPROVED,
    MissionState.ENGINEERING,
    MissionState.VERIFYING,
    MissionState.VERIFIED_RC,
    MissionState.OWNER_VALIDATION,
    MissionState.DISTRIBUTION_READY,
)
